services:
  db:
    image: postgres:17
    env_file:
      .env.db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bigdata"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      .env.web
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data

volumes:
  pgdata: